# Generated by Django 3.0.3 on 2020-12-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
